### ISSUE TITLE
Paragraph: Rewrite the following as a lambda function. Create a new column 'Review_Length'

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/dsc-0-04-04-lambda-functions-lab#1]
I guess, there is a typo in this function:
*
def rewrite_as_lambda(value):
    if len(value) > 50:
        return 'Short'
    elif len(value) < 80:
        return 'Medium'
    else:
        return 'Long'
*
You probably mean:
....
 if len(value) < 50: [smaller than]
        return 'Short'

**Comment by PeterBell** [comment]
Great point Britta - thanks. Just fixed with https://github.com/learn-co-curriculum/dsc-1-04-04-lambda-functions-lab/commit/3b106d9b8a63cc55fe58085b5a2c97ee0e5eb16f
