### ISSUE TITLE
Paragraph: Dates

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/dsc-0-04-04-lambda-functions-lab#2]
To select the month, the proposed solution in my opinion is wrong:
*
df.date.map(lambda x: x[-2:]) --> This mirrors the day.
*

It should be 
df.date.map(lambda x: x[5:7])

**Comment by PeterBell** [comment]
Hi Britta - good point. I'm going to close this for now as we're reworking the lessons and I'm going to go through to start to recreate the solution branches. Will bear this in mind, though - thanks!
